### PR TITLE
Fixed jpeg compatibility issue.

### PR DESCRIPTION
**Pull request by khanal-abhi**
I have fixed the jpeg compatibility issue. Now it works for jpeg input as well as output.

### CODE REVIEW

**Comment by dieforfree** [comment]
Still not working.  
JPEG reading has no problem, it does have a problem that the output file is totally black when you choose JPEG as output file format by set `-f JPEG`.  
FYI, QArt4J will NOT choose the output format based on the input file, but always by the `-f` parameter.  That is to say, the output format is PNG if you ignore the `-f` parameter.

**Comment by khanal-abhi** [comment]
Roger that. Was looking for something to do, thats perfect.

**Comment by khanal-abhi** [comment]
@dieforfree, i bypassed the -f flag and set the output file name as a .jpg file. I am using a mac so I don't know if I am getting an OS level conversion or legitimate conversion from the file but I have jpg input jpg output without any flags and the code as is.
I will double check the -f flag logic but could you see if passing in a .jpg that is actually a .jpg file file as an input and expecting the output to be a .jpg works for you?

**Comment by khanal-abhi** [comment]
It is fixed now.

**Comment by dieforfree** [comment]
@khanal-abhi Firstly, your sample-input.jpg is actually a PNG file, verify it by `exiftool -Format -S sample-input.jpg`.
And secondly, I think you have found the root cause which is a BufferedImage with alpha channel will give a black JPEG output. But your commit will lead output to losing alpha channel which may be not good to PNG.
Thirdly,  the deleted sample-output.png corrupts the README.md.

**Comment by khanal-abhi** [comment]
Ok, whoa. Did not mean to break it that bad. I will fix it and I will resort to my prior method where it will only lose alpha channel if it a JPEG output is necessary.

**Comment by maplecheck** [comment]
dieforfree, 你好，请加我QQ，有急事找你，五|四|四|零|七|零|二|三|四

**Pull request merged**
